name: Branch Created

# Trigger this action when a branch is created
on:
  create:
    branches:
      - '*'  # Listens to any branch creation

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

     - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clean LFS folders
        run: |
          git fetch --all
          git switch ${{ github.ref_name }}
          find data -type f -exec rm -f {} +
          git add .
          git commit -m 'LFS cleanup'
          git push
          
