name: Branch Created

# Trigger this action when a branch is created
on:
  create:
    branches:
      - '*'  # Listens to any branch creation
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
     
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Log branch creation
        run: |
          echo "Branch '${{ github.ref_name }}' has been created."
          
      - name: Perform LFS cleanup
        run: |
          git fetch --all
          git switch ${{ github.ref_name }}
          find data  -type f ! -name '.gitkeep' -exec rm -f {} +
          git add .
          git commit -m 'LFS cleanup'
          git push
