name: Branch Created

# Trigger this action when a branch is created
on:
  create:
    branches:
      - '*'  # Listens to any branch creation

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Clean LFS folders
        run: |
          find data -type f -exec rm -f {} +
          
